export const adminLocales = ["en", "fr"] as const;
export type AdminLocale = (typeof adminLocales)[number];

const en = {
  brand: "Falco",
  desk: "Room desk",
  overview: "Overview",
  hotels: "Hotels",
  purchases: "Purchases",
  agencies: "Agencies",
  requests: "Requests",
  allotments: "Allotments",
  publicSite: "Public site",
  logOut: "Log out",
  search: "Search",
  searchAllotments: "Search allotments, hotels",
  searchHotels: "Search hotels",
  searchRequests: "Search requests",
  searchAgencies: "Search agencies",
  searchPurchases: "Search purchases",
  noMatches: "No matches for “{query}” · {count} total",
  clearSearch: "Clear search",
  dismiss: "Dismiss",
  newCount: "{count} new",
  today: "Today",
  riyadh: "Riyadh",
  newHotel: "New hotel",
  hotel: "Hotel",
  selectHotel: "Select a hotel",
  cancelAction: "Cancel",
  deleteAction: "Delete",
  newPurchase: "New purchase",
  newAllotment: "New allotment",
  newAgency: "New agency",
  capacityToday: "Capacity — today",
  unitsAcross: "{count} units across {hotels} hotels",
  held: "Held",
  open: "Open",
  heldByCity: "Held by city",
  of: "of",
  capacityNote:
    "Held = rooms already allotted today. Open = still free of the rooms Falco has.",
  newToday: "{count} new today",
  openLabel: "open",
  allotmentRequest: "Allotment request",
  agencyApplication: "Agency application",
  draftPurchases: "Draft purchases",
  unconfirmed: "unconfirmed",
  roomTypes: "Room types",
  inHouse: "In house",
  upcoming: "Upcoming",
  upcomingStays: "Upcoming stays",
  closed: "Closed",
  latestAllotments: "Latest allotments",
  viewAll: "View all",
  hotelCount: "{count} hotels",
  noHotels: "No hotels yet.",
  editDetails: "Edit details",
  star: "{count}-star",
  roomTypeCount: "{count} room types",
  roomType: "Room type",
  sleeps: "Sleeps",
  heldToday: "Held today",
  free: "Free",
  priceNight: "Price / night (SAR)",
  pricePerNight: "Price / night",
  costNight: "Cost / night",
  agencyPriceNight: "Agency price / night",
  details: "Details",
  from: "From",
  to: "To",
  amount: "Amount",
  selectRoom: "Select a room",
  numberAssigned: "Number is assigned when you save.",
  orderedOn: "Ordered {date}",
  roomsAfterPurchase: "Rooms appear here after a purchase is confirmed.",
  photosAdded: "Photos — {count} added",
  photoRule: "Max 5 MB · JPG, PNG or WebP",
  addPhotos: "Add photos",
  dropFiles: "or drop files",
  remove: "Remove",
  retryPhoto: "Retry photo",
  photoError: "Use a JPG, PNG, or WebP photo under 5 MB.",
  requestsOpen: "{count} open",
  all: "All",
  allotment: "Allotment",
  agency: "Agency",
  noRequests:
    "No requests yet. Forms filled on the site appear here, and each agency is added to Agencies.",
  stepNew: "New",
  stepQuoted: "Quoted",
  stepConfirmed: "Confirmed block",
  stepDeclined: "Declined",
  markQuoted: "Mark quoted",
  confirming: "Confirming…",
  confirmPurchase: "Confirm purchase",
  confirmAllotment: "Confirm allotment",
  selectAgency: "Select an agency",
  draftNote: "A draft does not hold rooms. Confirming holds them for this agency.",
  saveDraft: "Save draft",
  saving: "Saving…",
  decline: "Decline",
  declining: "Declining…",
  emailTo: "Email {name}",
  statusSaved: "Every state change is saved on this request.",
  trip: "Trip",
  arrival: "Arrival",
  checkOut: "Check-out",
  checkIn: "Check-in",
  notes: "Notes",
  travellers: "Travellers",
  rooms: "Rooms",
  requestedRoom: "Requested room",
  contact: "Contact",
  role: "Role",
  website: "Website",
  markets: "Markets",
  requirements: "Requirements",
  markedQuoted: "Marked quoted — {email}",
  undone: "Undone",
  undo: "Undo",
  declinedToast: "Declined",
  allotmentCount: "{count} allotments",
  noAllotments:
    "No allotments yet. Create an allotment to hold rooms for an agency.",
  draft: "Draft",
  confirmed: "Confirmed",
  cancelled: "Cancelled",
  status: "Status",
  hotelRoom: "Hotel / room",
  qty: "Qty",
  stay: "Stay",
  nights: "Nights",
  cost: "Cost",
  sell: "Sell",
  margin: "Margin",
  releaseTitle: "Release allotment?",
  releaseBody:
    "{agency} holds {room} at {hotel} — {checkIn} → {checkOut}. Releasing frees this room for other agencies. This can't be undone.",
  releaseConfirm: "Release room",
  releasing: "Releasing…",
  keepAllotment: "Keep allotment",
  release: "Release",
  openRecord: "Open",
  noAllotmentRows: "No allotments yet.",
  showing: "Showing {visible} of {total}",
  number: "Number",
  period: "Period",
  total: "Total",
  noPurchases: "No purchases yet.",
  agencyName: "Agency name",
  country: "Country",
  email: "Email",
  phone: "Phone",
  saveAgency: "Save agency",
  noAgencies: "No agencies yet.",
  signIn: "Sign in",
  signInCopy: "Hotels, room costs, and agency allotments.",
  passwordRejected: "The password was not accepted.",
  passwordMissing: "Set ADMIN_PASSWORD in the environment before signing in.",
  password: "Password",
  english: "English",
  french: "Français",
  quantityError: "Only {count} rooms are free for those dates.",
  datesError: "Check-out must be after check-in.",
  spanError: "The rental period can't be longer than three years.",
  linesError: "Add at least one room before confirming the purchase.",
  roomLineError: "Each room needs a name, how many it sleeps, dates, and a price.",
  allotmentLinesError: "Add at least one room before confirming the allotment.",
  agencyError: "Select an agency.",
  cancelError:
    "Agencies still hold these rooms for those dates. Release the allotments first.",
  purchasedError:
    "This room comes from a confirmed purchase. Cancel that purchase before deleting the room.",
  allottedError: "This room is on an allotment. Cancel that allotment before deleting the room.",
  missingRoomError: "That room no longer exists.",
  invalidError: "Check the entered details and try again.",
  makkah: "Makkah",
  madinah: "Madinah",
  jeddah: "Jeddah",
} as const;

const fr: Record<keyof typeof en, string> = {
  brand: "Falco",
  desk: "Bureau des chambres",
  overview: "Tableau de bord",
  hotels: "Hôtels",
  purchases: "Achats",
  agencies: "Agences",
  requests: "Demandes",
  allotments: "Allotements",
  publicSite: "Site public",
  logOut: "Déconnexion",
  search: "Rechercher",
  searchAllotments: "Rechercher allotements, hôtels",
  searchHotels: "Rechercher un hôtel",
  searchRequests: "Rechercher une demande",
  searchAgencies: "Rechercher une agence",
  searchPurchases: "Rechercher un achat",
  noMatches: "Aucun résultat pour « {query} » · {count} au total",
  clearSearch: "Effacer",
  dismiss: "Fermer",
  newCount: "{count} nouv.",
  today: "Aujourd'hui",
  riyadh: "Riyad",
  newHotel: "Nouvel hôtel",
  hotel: "Hôtel",
  selectHotel: "Choisir un hôtel",
  cancelAction: "Annuler",
  deleteAction: "Supprimer",
  newPurchase: "Nouvel achat",
  newAllotment: "Nouvel allotement",
  newAgency: "Nouvelle agence",
  capacityToday: "Capacité — aujourd'hui",
  unitsAcross: "{count} unités dans {hotels} hôtels",
  held: "Occupé",
  open: "Libre",
  heldByCity: "Occupé par ville",
  of: "sur",
  capacityNote:
    "Occupé = chambres déjà attribuées aujourd'hui. Libre = encore disponibles parmi les chambres de Falco.",
  newToday: "{count} nouvelles aujourd'hui",
  openLabel: "ouvertes",
  allotmentRequest: "Demande d'allotement",
  agencyApplication: "Candidature d'agence",
  draftPurchases: "Achats en brouillon",
  unconfirmed: "non confirmés",
  roomTypes: "Types de chambres",
  inHouse: "En maison",
  upcoming: "À venir",
  upcomingStays: "Séjours à venir",
  closed: "Clos",
  latestAllotments: "Derniers allotements",
  viewAll: "Tout voir",
  hotelCount: "{count} hôtels",
  noHotels: "Aucun hôtel pour le moment.",
  editDetails: "Modifier",
  star: "{count} étoiles",
  roomTypeCount: "{count} types de chambres",
  roomType: "Type de chambre",
  sleeps: "Couchages",
  heldToday: "Occupées aujourd'hui",
  free: "Libres",
  priceNight: "Prix / nuit (SAR)",
  pricePerNight: "Prix / nuit",
  costNight: "Coût / nuit",
  agencyPriceNight: "Prix agence / nuit",
  details: "Détails",
  from: "Du",
  to: "Au",
  amount: "Montant",
  selectRoom: "Choisir une chambre",
  numberAssigned: "Le numéro est attribué à l'enregistrement.",
  orderedOn: "Commandé le {date}",
  roomsAfterPurchase: "Les chambres apparaissent ici après confirmation d'un achat.",
  photosAdded: "Photos — {count} ajoutées",
  photoRule: "5 Mo max · JPG, PNG ou WebP",
  addPhotos: "Ajouter des photos",
  dropFiles: "ou déposer des fichiers",
  remove: "Retirer",
  retryPhoto: "Réessayer la photo",
  photoError: "Utilisez un JPG, PNG ou WebP de moins de 5 Mo.",
  requestsOpen: "{count} ouvertes",
  all: "Toutes",
  allotment: "Allotement",
  agency: "Agence",
  noRequests:
    "Aucune demande pour le moment. Les formulaires du site apparaissent ici, et chaque agence est ajoutée aux Agences.",
  stepNew: "Nouveau",
  stepQuoted: "Devisé",
  stepConfirmed: "Bloc confirmé",
  stepDeclined: "Refusé",
  markQuoted: "Marquer devisé",
  confirming: "Confirmation…",
  confirmPurchase: "Confirmer l'achat",
  confirmAllotment: "Confirmer l'allotement",
  selectAgency: "Choisir une agence",
  draftNote: "Un brouillon ne réserve pas les chambres. La confirmation les bloque pour cette agence.",
  saveDraft: "Enregistrer le brouillon",
  saving: "Enregistrement…",
  decline: "Refuser",
  declining: "Refus…",
  emailTo: "Écrire à {name}",
  statusSaved: "Chaque changement est enregistré sur cette demande.",
  trip: "Séjour",
  arrival: "Arrivée",
  checkOut: "Départ",
  checkIn: "Arrivée",
  notes: "Notes",
  travellers: "Voyageurs",
  rooms: "Chambres",
  requestedRoom: "Chambre demandée",
  contact: "Contact",
  role: "Fonction",
  website: "Site web",
  markets: "Marchés",
  requirements: "Besoins",
  markedQuoted: "Marqué devisé — {email}",
  undone: "Annulé",
  undo: "Annuler",
  declinedToast: "Refusé",
  allotmentCount: "{count} allotements",
  noAllotments:
    "Aucun allotement pour le moment. Créez-en un pour réserver des chambres à une agence.",
  draft: "Brouillon",
  confirmed: "Confirmé",
  cancelled: "Annulé",
  status: "Statut",
  hotelRoom: "Hôtel / chambre",
  qty: "Qté",
  stay: "Séjour",
  nights: "Nuits",
  cost: "Coût",
  sell: "Vente",
  margin: "Marge",
  releaseTitle: "Libérer l'allotement ?",
  releaseBody:
    "{agency} détient {room} à {hotel} — {checkIn} → {checkOut}. La libération rend cette chambre disponible. Cette action est définitive.",
  releaseConfirm: "Libérer la chambre",
  releasing: "Libération…",
  keepAllotment: "Garder l'allotement",
  release: "Libérer",
  openRecord: "Ouvrir",
  noAllotmentRows: "Aucun allotement pour le moment.",
  showing: "{visible} sur {total}",
  number: "Numéro",
  period: "Période",
  total: "Total",
  noPurchases: "Aucun achat pour le moment.",
  agencyName: "Nom de l'agence",
  country: "Pays",
  email: "E-mail",
  phone: "Téléphone",
  saveAgency: "Enregistrer l'agence",
  noAgencies: "Aucune agence pour le moment.",
  signIn: "Connexion",
  signInCopy: "Hôtels, coûts des chambres et allotements des agences.",
  passwordRejected: "Le mot de passe n'a pas été accepté.",
  passwordMissing: "Définissez ADMIN_PASSWORD dans l'environnement avant de vous connecter.",
  password: "Mot de passe",
  english: "English",
  french: "Français",
  quantityError: "Il ne reste que {count} chambres libres pour ces dates.",
  datesError: "Le départ doit être après l'arrivée.",
  spanError: "La période ne peut pas dépasser trois ans.",
  linesError: "Ajoutez au moins une chambre avant de confirmer l'achat.",
  roomLineError: "Chaque chambre a besoin d'un nom, d'un nombre de couchages, de dates et d'un prix.",
  allotmentLinesError: "Ajoutez au moins une chambre avant de confirmer l'allotement.",
  agencyError: "Choisissez une agence.",
  cancelError:
    "Des agences détiennent encore ces chambres pour ces dates. Libérez d'abord les allotements.",
  purchasedError:
    "Cette chambre vient d'un achat confirmé. Annulez cet achat avant de supprimer la chambre.",
  allottedError:
    "Cette chambre est sur un allotement. Annulez cet allotement avant de supprimer la chambre.",
  missingRoomError: "Cette chambre n'existe plus.",
  invalidError: "Vérifiez les informations saisies et réessayez.",
  makkah: "La Mecque",
  madinah: "Médine",
  jeddah: "Djeddah",
};

export type AdminCopy = { [K in keyof typeof en]: string };

export function adminCopy(locale: AdminLocale): AdminCopy {
  return locale === "fr" ? fr : en;
}

export function fill(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}
