export const adminLocales = ["en", "fr"] as const;
export type AdminLocale = (typeof adminLocales)[number];

const en = {
  brand: "Falco",
  desk: "Room desk",
  deskGroup: "Desk",
  inventoryGroup: "Inventory",
  partnersGroup: "Partners",
  more: "More",
  closeMenu: "Close menu",
  mainNavigation: "Main navigation",
  mobileNavigation: "Mobile navigation",
  loading: "Loading",
  overview: "Overview",
  hotels: "Hotels",
  purchases: "Contracts",
  agencies: "Clients",
  agencyCount: "{count} clients",
  requests: "Requests",
  requestCount: "{count} requests",
  allotments: "Sales",
  saleChannel: "Source",
  channelDesk: "Desk",
  channelB2c: "Website B2C",
  channelB2b: "Website B2B",
  bookings: "Bookings",
  searchBookings: "Search bookings",
  bookingCount: "{count} bookings",
  noBookings: "No individual bookings yet.",
  pendingPayment: "Pending payment",
  guest: "Guest",
  publicSite: "Public site",
  logOut: "Log out",
  searchDesk: "Search hotels and sales",
  peg: "SAR / USD",
  pegRate: "3.7500",
  live: "Live",
  portfolioTitle: "Wholesale desk",
  portfolioNote: "Rooms bought from hotels, and rooms still held for clients.",
  wholesaleStock: "Wholesale stock",
  roomsAllocated: "rooms allocated",
  openToSell: "open today",
  checkedIn: "checked in",
  arrivals72: "Arrivals in 72 hours",
  activeHoldsLabel: "Active holds",
  roomsLocked: "rooms locked",
  nearestHold: "Nearest hold",
  noTimedHold: "No payment timer",
  grossWholesale: "Wholesale value",
  avgNight: "Average night",
  allocationTitle: "Allocation",
  property: "Property",
  allocated: "Rooms",
  staySpread: "Stay",
  contractValue: "Value",
  holdsInProgress: "Holds in progress",
  holdsNote: "Draft sales and unpaid bookings are still holding rooms.",
  releaseAction: "Release",
  allCities: "All cities",
  zone: "Zone",
  noAllocation: "No confirmed purchases yet.",
  search: "Search",
  searchAllotments: "Search sales, hotels",
  searchHotels: "Search hotels",
  searchRooms: "Search rooms, hotels",
  listedRoomCount: "{count} rooms",
  noRoomsYet: "No rooms yet. Confirm a purchase to add rooms.",
  searchRequests: "Search requests",
  searchAgencies: "Search clients",
  searchPurchases: "Search purchases",
  noMatches: "No matches for “{query}” · {count} total",
  clearSearch: "Clear search",
  dismiss: "Dismiss",
  newCount: "{count} new",
  today: "Today",
  riyadh: "Riyadh",
  newHotel: "New hotel",
  hotel: "Hotel",
  selectHotel: "Select a hotel",
  cancelAction: "Cancel",
  deleteAction: "Delete",
  newPurchase: "New purchase",
  newAllotment: "New sale",
  newAgency: "New client",
  capacityToday: "Capacity — today",
  unitsAcross: "{count} units across {hotels} hotels",
  held: "Held",
  open: "Open",
  heldByCity: "Held by city",
  of: "of",
  capacityNote:
    "Held = rooms already sold to agencies today. Open = still free of the rooms Falco has.",
  newToday: "{count} new today",
  openLabel: "open",
  allotmentRequest: "Sale request",
  agencyApplication: "Agency application",
  draftPurchases: "Draft purchases",
  unconfirmed: "unconfirmed",
  roomTypes: "Room types",
  inHouse: "In house",
  upcoming: "Upcoming",
  upcomingStays: "Upcoming stays",
  closed: "Closed",
  latestAllotments: "Latest sales",
  viewAll: "View all",
  hotelCount: "{count} hotels",
  noHotels: "No hotels yet.",
  editDetails: "Edit details",
  star: "{count}-star",
  roomTypeCount: "{count} room types",
  roomType: "Room type",
  solo: "Solo",
  double: "Double",
  triple: "Triple",
  quad: "Quad",
  roomOnly: "No meals",
  breakfastBoard: "Breakfast",
  halfBoard: "Half board",
  fullBoard: "Full board",
  typeView: "View",
  mealPlan: "Meals",
  newRoomType: "New room type",
  saveRoomType: "Save room type",
  deleteRoomType: "Delete room type",
  deleteRoomTypeTitle: "Delete this room type?",
  deleteRoomTypeBody:
    "This removes {name}. A type used by a room or a purchase stays.",
  roomTypeInUse: "This room type is used by a room or a purchase.",
  noRoomTypes: "No room types yet.",
  noFilteredRoomTypes: "No room types in this meal plan.",
  searchRoomTypes: "Search room types",
  filterRoomTypes: "Filter room types",
  roomTypeCountOne: "{count} room type",
  sleeps: "Sleeps",
  heldToday: "Held today",
  free: "Free",
  priceNight: "Price / night (SAR)",
  pricePerNight: "Price / night",
  costNight: "Cost / night",
  agencyPriceNight: "Agency price / night",
  details: "Details",
  from: "From",
  to: "To",
  calendar: "Calendar",
  normalCalendar: "Normal",
  arabicCalendar: "Arabic",
  amount: "Amount",
  selectRoom: "Select a room",
  numberAssigned: "Number is assigned when you save.",
  orderedOn: "Ordered {date}",
  roomsAfterPurchase: "Rooms appear here after a purchase is confirmed.",
  photosAdded: "Photos — {count} added",
  photoRule: "Max 5 MB · JPG, PNG or WebP",
  addPhotos: "Add photos",
  dropFiles: "or drop files",
  remove: "Remove",
  retryPhoto: "Retry photo",
  photoError: "Use a JPG, PNG, or WebP photo under 5 MB.",
  requestsOpen: "{count} open",
  all: "All",
  allotment: "Sale",
  agency: "Agency",
  individual: "Individual",
  client: "Client",
  clientName: "Name",
  fullName: "Full name",
  clientKind: "Type",
  clientRecord: "Client record",
  filterClients: "Filter clients",
  noFilteredClients: "No clients match this filter.",
  agencyHint: "A company buying rooms for groups.",
  individualHint: "A person buying rooms directly.",
  noRequests:
    "No requests yet. Forms filled on the site appear here, and each agency is added to Clients.",
  noFilteredRequests: "No requests match these filters.",
  stepNew: "New",
  stepQuoted: "Quoted",
  stepConfirmed: "Deal closed",
  stepDeclined: "Declined",
  markQuoted: "Mark quoted",
  confirming: "Confirming…",
  confirmPurchase: "Confirm purchase",
  confirmAllotment: "Confirm sale",
  salesOrder: "Sales order",
  orderDate: "Order date",
  orderLines: "Order lines",
  terms: "Terms and conditions",
  makeDraft: "Make draft",
  saveAllotment: "Save sale",
  selectAgency: "Select a client",
  chooseAgency: "Select an agency",
  draftNote:
    "A draft does not hold rooms. Confirming holds them for this client.",
  saveDraft: "Save draft",
  saving: "Saving…",
  decline: "Decline",
  declining: "Declining…",
  emailTo: "Email {name}",
  statusSaved: "Every state change is saved on this request.",
  trip: "Trip",
  arrival: "Arrival",
  checkOut: "Check-out",
  checkIn: "Check-in",
  notes: "Notes",
  travellers: "Travellers",
  rooms: "Rooms",
  requestedRoom: "Requested room",
  contact: "Contact",
  role: "Role",
  website: "Website",
  markets: "Markets",
  requirements: "Requirements",
  markedQuoted: "Marked quoted — {email}",
  undone: "Undone",
  undo: "Undo",
  declinedToast: "Declined",
  allotmentCount: "{count} sales",
  noAllotments:
    "No sales yet. Create a sale to hold rooms for an agency.",
  draft: "Draft",
  confirmed: "Confirmed",
  cancelled: "Cancelled",
  status: "Status",
  hotelRoom: "Hotel / room",
  qty: "Qty",
  stay: "Stay",
  nights: "Nights",
  cost: "Cost",
  sell: "Sell",
  margin: "Margin",
  releaseTitle: "Release this sale?",
  releaseBody:
    "{agency} holds {room} at {hotel} — {checkIn} → {checkOut}. Releasing frees this room for other agencies. This can't be undone.",
  releaseConfirm: "Release room",
  releasing: "Releasing…",
  keepAllotment: "Keep sale",
  release: "Release",
  openRecord: "Open",
  noAllotmentRows: "No sales yet.",
  showing: "Showing {visible} of {total}",
  number: "Number",
  period: "Period",
  total: "Total",
  purchaseCount: "{count} contracts",
  noPurchases: "No purchases yet.",
  agencyName: "Agency name",
  country: "Country",
  email: "Email",
  phone: "Phone",
  saveAgency: "Save client",
  noAgencies: "No clients yet.",
  signIn: "Sign in",
  signingIn: "Signing in…",
  signInCopy: "Hotels, room costs, and agency sales.",
  passwordRejected: "That email or password was not accepted.",
  passwordMissing: "Set ADMIN_PASSWORD in the environment before signing in.",
  createFirstAccount: "Create the first account",
  firstAccountCopy:
    "This desk has no accounts yet. This account can sign in and add the others.",
  accounts: "Accounts",
  accessGroup: "Access",
  settings: "Settings",
  company: "Company",
  companyPublicHint: "Shown on the public site: contact, about, and the footer.",
  companyName: "Company name",
  legalName: "Legal name",
  commercialRegistration: "Commercial registration",
  vatNumber: "VAT number",
  whatsappNumber: "WhatsApp number",
  saveSettings: "Save settings",
  companySaved: "Company details saved.",
  settingsIdentity: "Identity",
  settingsContact: "Contact",
  settingsRegistration: "Registration",
  settingsAddresses: "Addresses",
  newAccount: "New account",
  saveAccount: "Save account",
  deleteAccount: "Delete account",
  deleteAccountTitle: "Delete this account?",
  deleteAccountBody: "{name} will no longer be able to sign in.",
  lastAccount: "The last account stays.",
  cannotDeleteSelf: "You cannot delete the account you are signed in with.",
  emailTaken: "That email is already used.",
  accountName: "Name",
  passwordAgain: "Confirm password",
  passwordShort: "Use at least 8 characters.",
  passwordMismatch: "The two passwords do not match.",
  newPassword: "New password",
  newPasswordHint: "Leave blank to keep the current password.",
  accountYou: "You",
  accountCountOne: "{count} account",
  accountCount: "{count} accounts",
  searchAccounts: "Search accounts",
  sessionExpired: "Your session expired. Sign in again.",
  password: "Password",
  english: "English",
  french: "Français",
  switchToEnglish: "Switch to English",
  switchToFrench: "Switch to French",
  quantityError: "Only {count} rooms are free for those dates.",
  datesError: "Check-out must be after check-in.",
  saleWindowError:
    "The stay has to sit inside the purchased dates of every room on this sale.",
  saleWindowHint: "Purchased stay: {range}.",
  noRoomForStay: "No purchased room covers these dates.",
  saleRoomsClash:
    "These rooms were bought for different dates. One sale can only use rooms that share the stay.",
  datesSoldError:
    "Those dates still have a draft sale, a confirmed sale, or a booking. Change those first.",
  duplicateRoomError: "This hotel already has that room type for those dates.",
  roomStayHint:
    "A room is one type for one period. The same type on different dates is a separate room.",
  spanError: "The rental period can't be longer than three years.",
  linesError: "Add at least one room before confirming the purchase.",
  roomLineError:
    "Each room needs a name, how many it sleeps, dates, and a price.",
  allotmentLinesError: "Add at least one room before confirming the sale.",
  agencyError: "Select an agency.",
  cancelError:
    "Agencies still hold these rooms for those dates. Cancel those sales first.",
  purchasedError:
    "This room comes from a confirmed purchase. Cancel that purchase before deleting the room.",
  allottedError:
    "This room is already sold to an agency. Cancel that sale before deleting the room.",
  bookedError:
    "This room has an individual booking. Cancel that booking before deleting the room.",
  missingRoomError: "That room no longer exists.",
  purchaseError:
    "This purchase changed and can no longer be edited or deleted.",
  allotmentError:
    "This sale changed and can no longer be edited or deleted.",
  invalidError: "Check the entered details and try again.",
  filterByStatus: "Filter by status",
  filterRooms: "Filter rooms",
  activeRooms: "Active",
  outdatedRooms: "Outdated",
  noFilteredRooms: "No rooms match this filter.",
  activeRoomHolds: "Active room holds",
  activeRoomHoldsDescription:
    "Rooms currently occupied or reserved for an upcoming agency stay.",
  attention: "Needs attention",
  newRequests: "New requests",
  pendingPayments: "Pending payments",
  actionQueueEmpty: "Nothing needs attention right now.",
  addHotel: "Add hotel",
  hotelRecord: "Hotel record",
  saveHotel: "Save hotel",
  photos: "Photos",
  photoAlt: "{record} photo {count}",
  hotelName: "Hotel name",
  city: "City",
  stars: "Stars",
  distanceHaram: "Distance to the Haram",
  address: "Address",
  description: "Description",
  noPhotos: "No photos yet.",
  deleteHotel: "Delete hotel and its rooms",
  deleteHotelTitle: "Delete this hotel?",
  deleteHotelBody:
    "This permanently deletes {hotel} and its room records when no purchases, sales, or bookings block removal.",
  keepHotel: "Keep hotel",
  deleting: "Deleting…",
  roomsForHotel: "Rooms at this hotel",
  purchasesForHotel: "Purchases for this hotel",
  noPurchasesHotel: "No purchases for this hotel yet.",
  roomRecord: "Room record",
  ribbonHeld: "Held",
  ribbonOpen: "Open",
  ribbonSold: "Sold",
  inInventory: "Active in inventory",
  outOfInventory: "Not in inventory",
  roomDetailsTab: "Details and pricing",
  roomHoldsTab: "Agency holds",
  grossMargin: "Gross margin",
  spreadNight: "Spread / night",
  contractedStay: "Contracted stay",
  wholesaleCost: "Wholesale cost",
  noRoomPurchases: "No purchases are linked to this room.",
  noRoomHolds: "No agency holds on this room.",
  roomName: "Room name",
  guests: "Guests",
  roomsHeld: "Rooms held",
  publicPriceNight: "Public price / night (SAR)",
  publicPriceHint: "Leave blank to hide this room from individual travellers.",
  saveRoom: "Save room",
  allotRoom: "Sell this room",
  allotRoomDescription:
    "Choose an agency, stay dates, quantity, and private agency price.",
  quantityCostPurchase:
    "Quantity comes from confirmed purchases. Saving the cost updates this room and its current or upcoming purchases.",
  deleteRoom: "Delete room",
  deleteRoomTitle: "Delete this room?",
  deleteRoomBody:
    "This permanently deletes {room}. Existing purchases, sales, or bookings may prevent removal.",
  keepRoom: "Keep room",
  openToday: "Open today",
  soldToday: "Sold today",
  addLine: "Add a room line",
  addRoom: "Add a room",
  purchaseLineHelp:
    "Each line is one room type: how many rooms, how many people each room holds, the stay dates, the cost, and an optional public price. Leave the public price blank to hide the room from individual travellers.",
  roomNameExample: "Quad",
  roomDetailsExample: "Haram view, breakfast",
  notesExample: "Contract reference, payment terms",
  removeLine: "Remove line",
  linePricingError: "Each room needs Falco's cost and the agency price.",
  marginWithNights: "Margin · {count} nights",
  agencyBeforeAllotment: "Add a client before creating a sale.",
  noRoomsToAllot: "No rooms are ready to sell.",
  purchaseBeforeAllotment:
    "Confirm a hotel purchase before creating a sale.",
  hotelBeforePurchase: "Add a hotel before purchasing rooms.",
  purchaseConfirmedNotice:
    "Confirmed. Each room is now in inventory for the dates on its line.",
  purchaseCancelledNotice:
    "Cancelled. Its room capacity has been removed from inventory.",
  allotmentConfirmedNotice:
    "Confirmed. These rooms are held for {agency} from {checkIn} to {checkOut}.",
  allotmentCancelledNotice:
    "Cancelled. The rooms are available again for these dates.",
  bookingCancelledNotice:
    "Cancelled. The room hold has been released; payment refunds are handled separately.",
  cancelPurchaseTitle: "Cancel this purchase?",
  cancelPurchaseBody:
    "Cancelling {number} removes its confirmed room capacity when no agency holds depend on it.",
  keepPurchase: "Keep purchase",
  cancelAllotmentTitle: "Cancel this sale?",
  cancelAllotmentBody:
    "Cancelling {number} releases its rooms back to shared availability.",
  cancelBookingTitle: "Cancel this booking?",
  cancelBookingBody:
    "Cancelling {number} releases the rooms for other bookings. Payment refunds are handled separately.",
  keepBooking: "Keep booking",
  cancelling: "Cancelling…",
  deleteDraftTitle: "Delete this draft?",
  deleteDraftBody: "This permanently deletes {number}.",
  keepDraft: "Keep draft",
  deleteCancelledTitle: "Delete this cancelled record?",
  deleteCancelledBody: "This permanently deletes {number}. It is already cancelled.",
  keepCancelled: "Keep it",
  deleteRequestTitle: "Delete this request?",
  deleteRequestBody:
    "This permanently deletes {number}. The client record stays.",
  deleteBookingTitle: "Delete this booking?",
  deleteBookingBody:
    "This permanently deletes {number} and releases its rooms. Payment refunds are handled separately.",
  removePhotoTitle: "Remove this photo?",
  removePhotoBody: "The photo will be permanently removed from {record}.",
  keepPhoto: "Keep photo",
  removePhotoConfirm: "Remove photo",
  removing: "Removing…",
  bookingDetails: "Booking details",
  reference: "Reference",
  payment: "Payment",
  paymentReference: "Payment reference",
  holdUntil: "Hold until",
  createdAt: "Created",
  confirmedAt: "Confirmed at",
  whatsapp: "WhatsApp",
  openBooking: "Open booking",
  createAllotment: "Create sale",
  requestStatus: "Request status",
  requestStatusDescription:
    "This status tracks the conversation; inventory changes only when a sale is confirmed.",
  openRequest: "Open request",
  previous: "Back",
  makkah: "Makkah",
  madinah: "Madinah",
  jeddah: "Jeddah",
  requestCountOne: "{count} request",
  hotelCountOne: "{count} hotel",
  purchaseCountOne: "{count} purchase",
  allotmentCountOne: "{count} sale",
  agencyCountOne: "{count} client",
  bookingCountOne: "{count} booking",
  listedRoomCountOne: "{count} room",
  queueReview: "Review",
  queueConfirm: "Confirm",
  queueCollect: "Collect",
  setupTitle: "Get the desk running",
  setupIntro:
    "Capacity appears here once a confirmed purchase puts rooms on the calendar.",
  setupStepHotel: "Add your first hotel",
  setupStepPurchase: "Confirm a purchase to hold rooms",
  setupStepSale: "Create a sale for an agency",
  setupDone: "Done",
  minNights: "Minimum nights",
  bookNow: "Book now",
  requestBooking: "Request a booking",
  statusRequest: "Request",
  statusProvisional: "Provisional",
  statusNoShow: "No-show",
  holdSale: "Hold",
  saveRequest: "Save request",
  markNoShow: "Mark no-show",
  chartHeld: "Held",
  chartTaken: "Sold",
  chartFree: "Free",
  chartTitle: "Daily availability",
  chartEmpty: "Confirm a contract to see the daily chart.",
  agencyRates: "Company rates",
  rateNight: "Company price / night",
  portalEmail: "Login email",
  portalPassword: "Login password",
  portalPasswordHint: "Leave blank to keep the current password.",
  saveRate: "Save rate",
  noCompanyRate: "No company rate on this line yet.",
} as const;

const fr: Record<keyof typeof en, string> = {
  brand: "Falco",
  desk: "Bureau des chambres",
  deskGroup: "Bureau",
  inventoryGroup: "Inventaire",
  partnersGroup: "Partenaires",
  more: "Plus",
  closeMenu: "Fermer le menu",
  mainNavigation: "Navigation principale",
  mobileNavigation: "Navigation mobile",
  loading: "Chargement",
  overview: "Tableau de bord",
  hotels: "Hôtels",
  purchases: "Contrats",
  agencies: "Clients",
  agencyCount: "{count} clients",
  requests: "Demandes",
  requestCount: "{count} demandes",
  allotments: "Ventes",
  saleChannel: "Origine",
  channelDesk: "Bureau",
  channelB2c: "Site B2C",
  channelB2b: "Site B2B",
  bookings: "Réservations",
  searchBookings: "Rechercher des réservations",
  bookingCount: "{count} réservations",
  noBookings: "Aucune réservation individuelle pour le moment.",
  pendingPayment: "Paiement en attente",
  guest: "Hôte",
  publicSite: "Site public",
  logOut: "Déconnexion",
  searchDesk: "Rechercher hôtels et ventes",
  peg: "SAR / USD",
  pegRate: "3.7500",
  live: "En direct",
  portfolioTitle: "Bureau de gros",
  portfolioNote: "Chambres achetées aux hôtels, et chambres encore tenues pour des clients.",
  wholesaleStock: "Stock de gros",
  roomsAllocated: "chambres allouées",
  openToSell: "ouvertes aujourd'hui",
  checkedIn: "arrivées",
  arrivals72: "Arrivées sous 72 heures",
  activeHoldsLabel: "Blocages actifs",
  roomsLocked: "chambres bloquées",
  nearestHold: "Blocage le plus proche",
  noTimedHold: "Aucun minuteur de paiement",
  grossWholesale: "Valeur de gros",
  avgNight: "Nuit moyenne",
  allocationTitle: "Allocation",
  property: "Établissement",
  allocated: "Chambres",
  staySpread: "Séjour",
  contractValue: "Valeur",
  holdsInProgress: "Blocages en cours",
  holdsNote: "Les ventes en brouillon et les réservations impayées tiennent encore des chambres.",
  releaseAction: "Libérer",
  allCities: "Toutes les villes",
  zone: "Zone",
  noAllocation: "Aucun achat confirmé pour le moment.",
  search: "Rechercher",
  searchAllotments: "Rechercher ventes, hôtels",
  searchHotels: "Rechercher un hôtel",
  searchRooms: "Rechercher chambres, hôtels",
  listedRoomCount: "{count} chambres",
  noRoomsYet:
    "Aucune chambre pour le moment. Confirmez un achat pour en ajouter.",
  searchRequests: "Rechercher une demande",
  searchAgencies: "Rechercher un client",
  searchPurchases: "Rechercher un achat",
  noMatches: "Aucun résultat pour « {query} » · {count} au total",
  clearSearch: "Effacer",
  dismiss: "Fermer",
  newCount: "{count} nouv.",
  today: "Aujourd'hui",
  riyadh: "Riyad",
  newHotel: "Nouvel hôtel",
  hotel: "Hôtel",
  selectHotel: "Choisir un hôtel",
  cancelAction: "Annuler",
  deleteAction: "Supprimer",
  newPurchase: "Nouvel achat",
  newAllotment: "Nouvelle vente",
  newAgency: "Nouveau client",
  capacityToday: "Capacité — aujourd'hui",
  unitsAcross: "{count} unités dans {hotels} hôtels",
  held: "Occupé",
  open: "Libre",
  heldByCity: "Occupé par ville",
  of: "sur",
  capacityNote:
    "Occupé = chambres déjà attribuées aujourd'hui. Libre = encore disponibles parmi les chambres de Falco.",
  newToday: "{count} nouvelles aujourd'hui",
  openLabel: "ouvertes",
  allotmentRequest: "Demande de vente",
  agencyApplication: "Candidature d'agence",
  draftPurchases: "Achats en brouillon",
  unconfirmed: "non confirmés",
  roomTypes: "Types de chambres",
  inHouse: "En maison",
  upcoming: "À venir",
  upcomingStays: "Séjours à venir",
  closed: "Clos",
  latestAllotments: "Dernières ventes",
  viewAll: "Tout voir",
  hotelCount: "{count} hôtels",
  noHotels: "Aucun hôtel pour le moment.",
  editDetails: "Modifier",
  star: "{count} étoiles",
  roomTypeCount: "{count} types de chambres",
  roomType: "Type de chambre",
  solo: "Simple",
  double: "Double",
  triple: "Triple",
  quad: "Quadruple",
  roomOnly: "Sans repas",
  breakfastBoard: "Petit-déjeuner",
  halfBoard: "Demi-pension",
  fullBoard: "Pension complète",
  typeView: "Vue",
  mealPlan: "Repas",
  newRoomType: "Nouveau type",
  saveRoomType: "Enregistrer le type",
  deleteRoomType: "Supprimer le type",
  deleteRoomTypeTitle: "Supprimer ce type de chambre ?",
  deleteRoomTypeBody:
    "Cela supprime {name}. Un type utilisé par une chambre ou un achat reste.",
  roomTypeInUse: "Ce type est utilisé par une chambre ou un achat.",
  noRoomTypes: "Aucun type de chambre pour le moment.",
  noFilteredRoomTypes: "Aucun type pour ce repas.",
  searchRoomTypes: "Rechercher un type",
  filterRoomTypes: "Filtrer les types",
  roomTypeCountOne: "{count} type de chambre",
  sleeps: "Couchages",
  heldToday: "Détenues aujourd'hui",
  free: "Libres",
  priceNight: "Prix / nuit (SAR)",
  pricePerNight: "Prix / nuit",
  costNight: "Coût / nuit",
  agencyPriceNight: "Prix agence / nuit",
  details: "Détails",
  from: "Du",
  to: "Au",
  calendar: "Calendrier",
  normalCalendar: "Normal",
  arabicCalendar: "Arabe",
  amount: "Montant",
  selectRoom: "Choisir une chambre",
  numberAssigned: "Le numéro est attribué à l'enregistrement.",
  orderedOn: "Commandé le {date}",
  roomsAfterPurchase:
    "Les chambres apparaissent ici après confirmation d'un achat.",
  photosAdded: "Photos — {count} ajoutées",
  photoRule: "5 Mo max · JPG, PNG ou WebP",
  addPhotos: "Ajouter des photos",
  dropFiles: "ou déposer des fichiers",
  remove: "Retirer",
  retryPhoto: "Réessayer la photo",
  photoError: "Utilisez un JPG, PNG ou WebP de moins de 5 Mo.",
  requestsOpen: "{count} ouvertes",
  all: "Toutes",
  allotment: "Vente",
  agency: "Agence",
  individual: "Particulier",
  client: "Client",
  clientName: "Nom",
  fullName: "Nom complet",
  clientKind: "Type",
  clientRecord: "Fiche client",
  filterClients: "Filtrer les clients",
  noFilteredClients: "Aucun client ne correspond à ce filtre.",
  agencyHint: "Une société qui achète des chambres pour des groupes.",
  individualHint: "Une personne qui achète des chambres directement.",
  noRequests:
    "Aucune demande pour le moment. Les formulaires du site apparaissent ici, et chaque agence est ajoutée aux Clients.",
  noFilteredRequests: "Aucune demande ne correspond à ces filtres.",
  stepNew: "Nouveau",
  stepQuoted: "Devisé",
  stepConfirmed: "Dossier conclu",
  stepDeclined: "Refusé",
  markQuoted: "Marquer devisé",
  confirming: "Confirmation…",
  confirmPurchase: "Confirmer l'achat",
  confirmAllotment: "Confirmer la vente",
  salesOrder: "Bon de vente",
  orderDate: "Date de commande",
  orderLines: "Lignes",
  terms: "Conditions",
  makeDraft: "Repasser en brouillon",
  saveAllotment: "Enregistrer la vente",
  selectAgency: "Choisir un client",
  chooseAgency: "Choisir une agence",
  draftNote:
    "Un brouillon ne réserve pas les chambres. La confirmation les bloque pour ce client.",
  saveDraft: "Enregistrer le brouillon",
  saving: "Enregistrement…",
  decline: "Refuser",
  declining: "Refus…",
  emailTo: "Écrire à {name}",
  statusSaved: "Chaque changement est enregistré sur cette demande.",
  trip: "Séjour",
  arrival: "Arrivée",
  checkOut: "Départ",
  checkIn: "Arrivée",
  notes: "Notes",
  travellers: "Personnes",
  rooms: "Chambres",
  requestedRoom: "Chambre demandée",
  contact: "Contact",
  role: "Fonction",
  website: "Site web",
  markets: "Marchés",
  requirements: "Besoins",
  markedQuoted: "Marqué devisé — {email}",
  undone: "Annulé",
  undo: "Annuler",
  declinedToast: "Refusé",
  allotmentCount: "{count} ventes",
  noAllotments:
    "Aucune vente pour le moment. Créez-en une pour réserver des chambres à une agence.",
  draft: "Brouillon",
  confirmed: "Confirmé",
  cancelled: "Annulé",
  status: "Statut",
  hotelRoom: "Hôtel / chambre",
  qty: "Qté",
  stay: "Séjour",
  nights: "Nuits",
  cost: "Coût",
  sell: "Vente",
  margin: "Marge",
  releaseTitle: "Libérer cette vente ?",
  releaseBody:
    "{agency} détient {room} à {hotel} — {checkIn} → {checkOut}. La libération rend cette chambre disponible. Cette action est définitive.",
  releaseConfirm: "Libérer la chambre",
  releasing: "Libération…",
  keepAllotment: "Garder la vente",
  release: "Libérer",
  openRecord: "Ouvrir",
  noAllotmentRows: "Aucune vente pour le moment.",
  showing: "{visible} sur {total}",
  number: "Numéro",
  period: "Période",
  total: "Total",
  purchaseCount: "{count} contrats",
  noPurchases: "Aucun achat pour le moment.",
  agencyName: "Nom de l'agence",
  country: "Pays",
  email: "E-mail",
  phone: "Téléphone",
  saveAgency: "Enregistrer le client",
  noAgencies: "Aucun client pour le moment.",
  signIn: "Connexion",
  signingIn: "Connexion…",
  signInCopy: "Hôtels, coûts des chambres et ventes aux agences.",
  passwordRejected: "Cet e-mail ou ce mot de passe n'a pas été accepté.",
  passwordMissing:
    "Définissez ADMIN_PASSWORD dans l'environnement avant de vous connecter.",
  createFirstAccount: "Créer le premier compte",
  firstAccountCopy:
    "Ce bureau n'a encore aucun compte. Ce compte pourra se connecter et ajouter les autres.",
  accounts: "Comptes",
  accessGroup: "Accès",
  settings: "Réglages",
  company: "Société",
  companyPublicHint: "Affiché sur le site public : contact, à propos et le pied de page.",
  companyName: "Nom de la société",
  legalName: "Raison sociale",
  commercialRegistration: "Registre de commerce",
  vatNumber: "Numéro de TVA",
  whatsappNumber: "Numéro WhatsApp",
  saveSettings: "Enregistrer les réglages",
  companySaved: "Informations de la société enregistrées.",
  settingsIdentity: "Identité",
  settingsContact: "Contact",
  settingsRegistration: "Immatriculation",
  settingsAddresses: "Adresses",
  newAccount: "Nouveau compte",
  saveAccount: "Enregistrer le compte",
  deleteAccount: "Supprimer le compte",
  deleteAccountTitle: "Supprimer ce compte ?",
  deleteAccountBody: "{name} ne pourra plus se connecter.",
  lastAccount: "Le dernier compte reste.",
  cannotDeleteSelf: "Vous ne pouvez pas supprimer le compte avec lequel vous êtes connecté.",
  emailTaken: "Cet e-mail est déjà utilisé.",
  accountName: "Nom",
  passwordAgain: "Confirmer le mot de passe",
  passwordShort: "Au moins 8 caractères.",
  passwordMismatch: "Les deux mots de passe ne correspondent pas.",
  newPassword: "Nouveau mot de passe",
  newPasswordHint: "Laisser vide pour conserver le mot de passe actuel.",
  accountYou: "Vous",
  accountCountOne: "{count} compte",
  accountCount: "{count} comptes",
  searchAccounts: "Rechercher un compte",
  sessionExpired: "Votre session a expiré. Reconnectez-vous.",
  password: "Mot de passe",
  english: "English",
  french: "Français",
  switchToEnglish: "Passer à l'anglais",
  switchToFrench: "Passer au français",
  quantityError: "Il ne reste que {count} chambres libres pour ces dates.",
  datesError: "Le départ doit être après l'arrivée.",
  saleWindowError:
    "Le séjour doit rester dans les dates achetées de chaque chambre de cette vente.",
  saleWindowHint: "Séjour acheté : {range}.",
  noRoomForStay: "Aucune chambre achetée ne couvre ces dates.",
  saleRoomsClash:
    "Ces chambres ont été achetées sur des dates différentes. Une vente ne peut utiliser que des chambres qui partagent le séjour.",
  datesSoldError:
    "Ces dates ont encore une vente brouillon, une vente confirmée ou une réservation. Modifiez-les d'abord.",
  duplicateRoomError:
    "Cet hôtel a déjà ce type de chambre pour ces dates.",
  roomStayHint:
    "Une chambre est un type pour une période. Le même type à d'autres dates est une autre chambre.",
  spanError: "La période ne peut pas dépasser trois ans.",
  linesError: "Ajoutez au moins une chambre avant de confirmer l'achat.",
  roomLineError:
    "Chaque chambre a besoin d'un nom, d'un nombre de couchages, de dates et d'un prix.",
  allotmentLinesError:
    "Ajoutez au moins une chambre avant de confirmer la vente.",
  agencyError: "Choisissez une agence.",
  cancelError:
    "Des agences détiennent encore ces chambres pour ces dates. Annulez d'abord ces ventes.",
  purchasedError:
    "Cette chambre vient d'un achat confirmé. Annulez cet achat avant de supprimer la chambre.",
  allottedError:
    "Cette chambre est déjà vendue à une agence. Annulez cette vente avant de supprimer la chambre.",
  bookedError:
    "Cette chambre a une réservation individuelle. Annulez-la avant de supprimer la chambre.",
  missingRoomError: "Cette chambre n'existe plus.",
  purchaseError: "Cet achat a changé et ne peut plus être modifié ou supprimé.",
  allotmentError:
    "Cette vente a changé et ne peut plus être modifiée ou supprimée.",
  invalidError: "Vérifiez les informations saisies et réessayez.",
  filterByStatus: "Filtrer par statut",
  filterRooms: "Filtrer les chambres",
  activeRooms: "Actives",
  outdatedRooms: "Passées",
  noFilteredRooms: "Aucune chambre ne correspond à ce filtre.",
  activeRoomHolds: "Blocages de chambres actifs",
  activeRoomHoldsDescription:
    "Chambres occupées ou réservées pour un prochain séjour d'agence.",
  attention: "À traiter",
  newRequests: "Nouvelles demandes",
  pendingPayments: "Paiements en attente",
  actionQueueEmpty: "Aucune action urgente pour le moment.",
  addHotel: "Ajouter un hôtel",
  hotelRecord: "Fiche de l'hôtel",
  saveHotel: "Enregistrer l'hôtel",
  photos: "Photos",
  photoAlt: "Photo {count} de {record}",
  hotelName: "Nom de l'hôtel",
  city: "Ville",
  stars: "Étoiles",
  distanceHaram: "Distance du Haram",
  address: "Adresse",
  description: "Description",
  noPhotos: "Aucune photo pour le moment.",
  deleteHotel: "Supprimer l'hôtel et ses chambres",
  deleteHotelTitle: "Supprimer cet hôtel ?",
  deleteHotelBody:
    "Cette action supprime définitivement {hotel} et ses chambres si aucun achat, aucune vente ou aucune réservation ne bloque la suppression.",
  keepHotel: "Garder l'hôtel",
  deleting: "Suppression…",
  roomsForHotel: "Chambres de cet hôtel",
  purchasesForHotel: "Achats de cet hôtel",
  noPurchasesHotel: "Aucun achat pour cet hôtel.",
  roomRecord: "Fiche de la chambre",
  ribbonHeld: "Retenu",
  ribbonOpen: "Libre",
  ribbonSold: "Vendu",
  inInventory: "En stock",
  outOfInventory: "Hors stock",
  roomDetailsTab: "Détails et prix",
  roomHoldsTab: "Blocages agence",
  grossMargin: "Marge brute",
  spreadNight: "Écart / nuit",
  contractedStay: "Séjour acheté",
  wholesaleCost: "Coût de gros",
  noRoomPurchases: "Aucun achat n'est lié à cette chambre.",
  noRoomHolds: "Aucun blocage d'agence sur cette chambre.",
  roomName: "Nom de la chambre",
  guests: "Personnes",
  roomsHeld: "Chambres détenues",
  publicPriceNight: "Prix public / nuit (SAR)",
  publicPriceHint:
    "Laissez vide pour masquer cette chambre aux particuliers.",
  saveRoom: "Enregistrer la chambre",
  allotRoom: "Vendre cette chambre",
  allotRoomDescription:
    "Choisissez une agence, les dates, la quantité et le prix privé agence.",
  quantityCostPurchase:
    "La quantité provient des achats confirmés. Enregistrer le coût met à jour cette chambre et ses achats en cours ou à venir.",
  deleteRoom: "Supprimer la chambre",
  deleteRoomTitle: "Supprimer cette chambre ?",
  deleteRoomBody:
    "Cette action supprime définitivement {room}. Des achats, ventes ou réservations peuvent l'empêcher.",
  keepRoom: "Garder la chambre",
  openToday: "Libres aujourd'hui",
  soldToday: "Vendues aujourd'hui",
  addLine: "Ajouter une ligne de chambre",
  addRoom: "Ajouter une chambre",
  purchaseLineHelp:
    "Chaque ligne est un type de chambre : le nombre de chambres, le nombre de personnes par chambre, les dates, le coût, et un prix public facultatif. Laissez le prix public vide pour masquer la chambre aux particuliers.",
  roomNameExample: "Quadruple",
  roomDetailsExample: "Vue Haram, petit-déjeuner",
  notesExample: "Référence du contrat, conditions de paiement",
  removeLine: "Retirer la ligne",
  linePricingError:
    "Chaque chambre doit avoir le coût Falco et le prix agence.",
  marginWithNights: "Marge · {count} nuits",
  agencyBeforeAllotment: "Ajoutez un client avant de créer une vente.",
  noRoomsToAllot: "Aucune chambre prête à être vendue.",
  purchaseBeforeAllotment:
    "Confirmez un achat hôtelier avant de créer une vente.",
  hotelBeforePurchase: "Ajoutez un hôtel avant d'acheter des chambres.",
  purchaseConfirmedNotice:
    "Confirmé. Chaque chambre est maintenant en stock pour les dates de sa ligne.",
  purchaseCancelledNotice:
    "Annulé. La capacité correspondante a été retirée du stock.",
  allotmentConfirmedNotice:
    "Confirmé. Ces chambres sont bloquées pour {agency} du {checkIn} au {checkOut}.",
  allotmentCancelledNotice:
    "Annulé. Les chambres sont de nouveau disponibles pour ces dates.",
  bookingCancelledNotice:
    "Annulée. Le blocage des chambres est libéré ; les remboursements sont traités séparément.",
  cancelPurchaseTitle: "Annuler cet achat ?",
  cancelPurchaseBody:
    "L'annulation de {number} retire sa capacité confirmée si aucune vente n'en dépend.",
  keepPurchase: "Garder l'achat",
  cancelAllotmentTitle: "Annuler cette vente ?",
  cancelAllotmentBody:
    "L'annulation de {number} remet ses chambres dans la disponibilité partagée.",
  cancelBookingTitle: "Annuler cette réservation ?",
  cancelBookingBody:
    "L'annulation de {number} libère les chambres. Les remboursements sont gérés séparément.",
  keepBooking: "Garder la réservation",
  cancelling: "Annulation…",
  deleteDraftTitle: "Supprimer ce brouillon ?",
  deleteDraftBody: "Cette action supprime définitivement {number}.",
  keepDraft: "Garder le brouillon",
  deleteCancelledTitle: "Supprimer cet élément annulé ?",
  deleteCancelledBody:
    "Cette action supprime définitivement {number}. Il est déjà annulé.",
  keepCancelled: "Le garder",
  deleteRequestTitle: "Supprimer cette demande ?",
  deleteRequestBody:
    "Cette action supprime définitivement {number}. La fiche client reste.",
  deleteBookingTitle: "Supprimer cette réservation ?",
  deleteBookingBody:
    "Cette action supprime définitivement {number} et libère ses chambres. Les remboursements sont gérés séparément.",
  removePhotoTitle: "Retirer cette photo ?",
  removePhotoBody: "La photo sera définitivement retirée de {record}.",
  keepPhoto: "Garder la photo",
  removePhotoConfirm: "Retirer la photo",
  removing: "Suppression…",
  bookingDetails: "Détails de la réservation",
  reference: "Référence",
  payment: "Paiement",
  paymentReference: "Référence du paiement",
  holdUntil: "Blocage jusqu'au",
  createdAt: "Créée le",
  confirmedAt: "Confirmée le",
  whatsapp: "WhatsApp",
  openBooking: "Ouvrir la réservation",
  createAllotment: "Créer une vente",
  requestStatus: "Statut de la demande",
  requestStatusDescription:
    "Ce statut suit l'échange commercial ; le stock change uniquement quand une vente est confirmée.",
  openRequest: "Ouvrir la demande",
  previous: "Retour",
  makkah: "La Mecque",
  madinah: "Médine",
  jeddah: "Djeddah",
  requestCountOne: "{count} demande",
  hotelCountOne: "{count} hôtel",
  purchaseCountOne: "{count} achat",
  allotmentCountOne: "{count} vente",
  agencyCountOne: "{count} client",
  bookingCountOne: "{count} réservation",
  listedRoomCountOne: "{count} chambre",
  queueReview: "Traiter",
  queueConfirm: "Confirmer",
  queueCollect: "Encaisser",
  setupTitle: "Mettre le bureau en route",
  setupIntro:
    "La capacité s'affiche dès qu'un achat confirmé ajoute des chambres au calendrier.",
  setupStepHotel: "Ajouter votre premier hôtel",
  setupStepPurchase: "Confirmer un achat pour bloquer des chambres",
  setupStepSale: "Créer une vente pour une agence",
  setupDone: "Terminé",
  minNights: "Nuits minimum",
  bookNow: "Réserver",
  requestBooking: "Demander une réservation",
  statusRequest: "Demande",
  statusProvisional: "Provisoire",
  statusNoShow: "No-show",
  holdSale: "Bloquer",
  saveRequest: "Enregistrer la demande",
  markNoShow: "Marquer no-show",
  chartHeld: "Tenues",
  chartTaken: "Vendues",
  chartFree: "Libres",
  chartTitle: "Disponibilité quotidienne",
  chartEmpty: "Confirmez un contrat pour voir le tableau quotidien.",
  agencyRates: "Tarifs société",
  rateNight: "Prix société / nuit",
  portalEmail: "E-mail de connexion",
  portalPassword: "Mot de passe",
  portalPasswordHint: "Laissez vide pour garder le mot de passe actuel.",
  saveRate: "Enregistrer le tarif",
  noCompanyRate: "Aucun tarif société sur cette ligne.",
};

export type AdminCopy = { [K in keyof typeof en]: string };

export function adminCopy(locale: AdminLocale): AdminCopy {
  return locale === "fr" ? fr : en;
}

export function fill(
  template: string,
  values: Record<string, string | number>,
) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) =>
    String(values[key] ?? ""),
  );
}

export function countText(
  count: number,
  one: string,
  many: string,
): string {
  return fill(count === 1 ? one : many, { count });
}
